name: Deploy Flutter Web to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable "$HOME/flutter"
          echo "$HOME/flutter/bin" >> "$GITHUB_PATH"

      - name: Enable web
        run: flutter config --enable-web

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=build/web --site="$NETLIFY_SITE_ID" --auth="$NETLIFY_AUTH_TOKEN"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
